/*
 Navicat Premium Data Transfer

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 50731
 Source Host           : localhost:3306
 Source Schema         : pap2021

 Target Server Type    : MySQL
 Target Server Version : 50731
 File Encoding         : 65001

 Date: 06/07/2021 12:45:33
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for calendario
-- ----------------------------
DROP TABLE IF EXISTS `calendario`;
CREATE TABLE `calendario`  (
  `calendarioId` int(11) NOT NULL,
  `calendarioNome` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `calendarioData` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `calendarioVencedor` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `calendarioNacionalidade` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`calendarioId`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of calendario
-- ----------------------------
INSERT INTO `calendario` VALUES (1, 'asdas', '123', 'asdasd', 'asdasd');

-- ----------------------------
-- Table structure for marcas
-- ----------------------------
DROP TABLE IF EXISTS `marcas`;
CREATE TABLE `marcas`  (
  `marcasId` int(11) NOT NULL,
  `marcasNome` varchar(10) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `marcasCavalagem` int(11) NULL DEFAULT NULL,
  `marcasMotor` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `marcasDiam` decimal(2, 0) NOT NULL,
  `marcasBinario` int(11) NOT NULL,
  `marcasTrans` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `marcasCaixa` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `marcasImgUrl` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`marcasId`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of marcas
-- ----------------------------
INSERT INTO `marcas` VALUES (1, 'uisabhdfui', 380, 'said', 1, 123123, 'fdgjknfd', 'osdfgnd', 'images/img-1.jpg');
INSERT INTO `marcas` VALUES (2, 'sfs', 333, 'asd', 2, 1234, '', 'sdfsd', 'images/percurso1.jpg');

-- ----------------------------
-- Table structure for pais
-- ----------------------------
DROP TABLE IF EXISTS `pais`;
CREATE TABLE `pais`  (
  `paisId` tinyint(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `paisNome` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  `paisName` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL,
  PRIMARY KEY (`paisId`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 253 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of pais
-- ----------------------------
INSERT INTO `pais` VALUES (1, 'AFEGANISTÃO', 'AFGHANISTAN');
INSERT INTO `pais` VALUES (2, 'ACROTÍRI E DECELIA', 'AKROTIRI E DEKÉLIA');
INSERT INTO `pais` VALUES (3, 'ÁFRICA DO SUL', 'SOUTH AFRICA');
INSERT INTO `pais` VALUES (4, 'ALBÂNIA', 'ALBANIA');
INSERT INTO `pais` VALUES (5, 'ALEMANHA', 'GERMANY');
INSERT INTO `pais` VALUES (6, 'AMERICAN SAMOA', 'AMERICAN SAMOA');
INSERT INTO `pais` VALUES (7, 'ANDORRA', 'ANDORRA');
INSERT INTO `pais` VALUES (8, 'ANGOLA', 'ANGOLA');
INSERT INTO `pais` VALUES (9, 'ANGUILLA', 'ANGUILLA');
INSERT INTO `pais` VALUES (10, 'ANTÍGUA E BARBUDA', 'ANTIGUA AND BARBUDA');
INSERT INTO `pais` VALUES (11, 'ANTILHAS NEERLANDESAS', 'NETHERLANDS ANTILLES');
INSERT INTO `pais` VALUES (12, 'ARÁBIA SAUDITA', 'SAUDI ARABIA');
INSERT INTO `pais` VALUES (13, 'ARGÉLIA', 'ALGERIA');
INSERT INTO `pais` VALUES (14, 'ARGENTINA', 'ARGENTINA');
INSERT INTO `pais` VALUES (15, 'ARMÉNIA', 'ARMENIA');
INSERT INTO `pais` VALUES (16, 'ARUBA', 'ARUBA');
INSERT INTO `pais` VALUES (17, 'AUSTRÁLIA', 'AUSTRALIA');
INSERT INTO `pais` VALUES (18, 'ÁUSTRIA', 'AUSTRIA');
INSERT INTO `pais` VALUES (19, 'AZERBAIJÃO', 'AZERBAIJAN');
INSERT INTO `pais` VALUES (20, 'BAHAMAS', 'BAHAMAS, THE');
INSERT INTO `pais` VALUES (21, 'BANGLADECHE', 'BANGLADESH');
INSERT INTO `pais` VALUES (22, 'BARBADOS', 'BARBADOS');
INSERT INTO `pais` VALUES (23, 'BARÉM', 'BAHRAIN');
INSERT INTO `pais` VALUES (24, 'BASSAS DA ÍNDIA', 'BASSAS DA INDIA');
INSERT INTO `pais` VALUES (25, 'BÉLGICA', 'BELGIUM');
INSERT INTO `pais` VALUES (26, 'BELIZE', 'BELIZE');
INSERT INTO `pais` VALUES (27, 'BENIM', 'BENIN');
INSERT INTO `pais` VALUES (28, 'BERMUDAS', 'BERMUDA');
INSERT INTO `pais` VALUES (29, 'BIELORRÚSSIA', 'BELARUS');
INSERT INTO `pais` VALUES (30, 'BOLÍVIA', 'BOLIVIA');
INSERT INTO `pais` VALUES (31, 'BÓSNIA E HERZEGOVINA', 'BOSNIA AND HERZEGOVINA');
INSERT INTO `pais` VALUES (32, 'BOTSUANA', 'BOTSWANA');
INSERT INTO `pais` VALUES (33, 'BRASIL', 'BRAZIL');
INSERT INTO `pais` VALUES (34, 'BRUNEI DARUSSALAM', 'BRUNEI DARUSSALAM');
INSERT INTO `pais` VALUES (35, 'BULGÁRIA', 'BULGARIA');
INSERT INTO `pais` VALUES (36, 'BURQUINA FASO', 'BURKINA FASO');
INSERT INTO `pais` VALUES (37, 'BURUNDI', 'BURUNDI');
INSERT INTO `pais` VALUES (38, 'BUTÃO', 'BHUTAN');
INSERT INTO `pais` VALUES (39, 'CABO VERDE', 'CAPE VERDE');
INSERT INTO `pais` VALUES (40, 'CAMARÕES', 'CAMEROON');
INSERT INTO `pais` VALUES (41, 'CAMBOJA', 'CAMBODIA');
INSERT INTO `pais` VALUES (42, 'CANADÁ', 'CANADA');
INSERT INTO `pais` VALUES (43, 'CATAR', 'QATAR');
INSERT INTO `pais` VALUES (44, 'CAZAQUISTÃO', 'KAZAKHSTAN');
INSERT INTO `pais` VALUES (45, 'CENTRO-AFRICANA REPÚBLICA', 'CENTRAL AFRICAN REPUBLIC');
INSERT INTO `pais` VALUES (46, 'CHADE', 'CHAD');
INSERT INTO `pais` VALUES (47, 'CHILE', 'CHILE');
INSERT INTO `pais` VALUES (48, 'CHINA', 'CHINA');
INSERT INTO `pais` VALUES (49, 'CHIPRE', 'CYPRUS');
INSERT INTO `pais` VALUES (50, 'COLÔMBIA', 'COLOMBIA');
INSERT INTO `pais` VALUES (51, 'COMORES', 'COMOROS');
INSERT INTO `pais` VALUES (52, 'CONGO', 'CONGO');
INSERT INTO `pais` VALUES (53, 'CONGO REPÚBLICA DEMOCRÁTICA', 'CONGO DEMOCRATIC REPUBLIC');
INSERT INTO `pais` VALUES (54, 'COREIA DO NORTE', 'KOREA NORTH');
INSERT INTO `pais` VALUES (55, 'COREIA DO SUL', 'KOREA SOUTH');
INSERT INTO `pais` VALUES (56, 'COSTA DO MARFIM', 'IVORY COAST');
INSERT INTO `pais` VALUES (57, 'COSTA RICA', 'COSTA RICA');
INSERT INTO `pais` VALUES (58, 'CROÁCIA', 'CROATIA');
INSERT INTO `pais` VALUES (59, 'CUBA', 'CUBA');
INSERT INTO `pais` VALUES (60, 'DINAMARCA', 'DENMARK');
INSERT INTO `pais` VALUES (61, 'DOMÍNICA', 'DOMINICA');
INSERT INTO `pais` VALUES (62, 'EGIPTO', 'EGYPT');
INSERT INTO `pais` VALUES (63, 'EMIRADOS ÁRABES UNIDOS', 'UNITED ARAB EMIRATES');
INSERT INTO `pais` VALUES (64, 'EQUADOR', 'ECUADOR');
INSERT INTO `pais` VALUES (65, 'ERITREIA', 'ERITREA');
INSERT INTO `pais` VALUES (66, 'ESLOVÁQUIA', 'SLOVAKIA');
INSERT INTO `pais` VALUES (67, 'ESLOVÉNIA', 'SLOVENIA');
INSERT INTO `pais` VALUES (68, 'ESPANHA', 'SPAIN');
INSERT INTO `pais` VALUES (69, 'ESTADOS UNIDOS', 'UNITED STATES');
INSERT INTO `pais` VALUES (70, 'ESTÓNIA', 'ESTONIA');
INSERT INTO `pais` VALUES (71, 'ETIÓPIA', 'ETHIOPIA');
INSERT INTO `pais` VALUES (72, 'FAIXA DE GAZA', 'GAZA STRIP');
INSERT INTO `pais` VALUES (73, 'FIJI', 'FIJI');
INSERT INTO `pais` VALUES (74, 'FILIPINAS', 'PHILIPPINES');
INSERT INTO `pais` VALUES (75, 'FINLÂNDIA', 'FINLAND');
INSERT INTO `pais` VALUES (76, 'FRANÇA', 'FRANCE');
INSERT INTO `pais` VALUES (77, 'GABÃO', 'GABON');
INSERT INTO `pais` VALUES (78, 'GÂMBIA', 'GAMBIA');
INSERT INTO `pais` VALUES (79, 'GANA', 'GHANA');
INSERT INTO `pais` VALUES (80, 'GEÓRGIA', 'GEORGIA');
INSERT INTO `pais` VALUES (81, 'GIBRALTAR', 'GIBRALTAR');
INSERT INTO `pais` VALUES (82, 'GRANADA', 'GRENADA');
INSERT INTO `pais` VALUES (83, 'GRÉCIA', 'GREECE');
INSERT INTO `pais` VALUES (84, 'GRONELÂNDIA', 'GREENLAND');
INSERT INTO `pais` VALUES (85, 'GUADALUPE', 'GUADELOUPE');
INSERT INTO `pais` VALUES (86, 'GUAM', 'GUAM');
INSERT INTO `pais` VALUES (87, 'GUATEMALA', 'GUATEMALA');
INSERT INTO `pais` VALUES (88, 'GUERNSEY', 'GUERNSEY');
INSERT INTO `pais` VALUES (89, 'GUIANA', 'GUYANA');
INSERT INTO `pais` VALUES (90, 'GUIANA FRANCESA', 'FRENCH GUIANA');
INSERT INTO `pais` VALUES (91, 'GUINÉ', 'GUINEA');
INSERT INTO `pais` VALUES (92, 'GUINÉ EQUATORIAL', 'EQUATORIAL GUINEA');
INSERT INTO `pais` VALUES (93, 'GUINÉ-BISSAU', 'GUINEA-BISSAU');
INSERT INTO `pais` VALUES (94, 'HAITI', 'HAITI');
INSERT INTO `pais` VALUES (95, 'HONDURAS', 'HONDURAS');
INSERT INTO `pais` VALUES (96, 'HONG KONG', 'HONG KONG');
INSERT INTO `pais` VALUES (97, 'HUNGRIA', 'HUNGARY');
INSERT INTO `pais` VALUES (98, 'IÉMEN', 'YEMEN');
INSERT INTO `pais` VALUES (99, 'ILHA BOUVET', 'BOUVET ISLAND');
INSERT INTO `pais` VALUES (100, 'ILHA CHRISTMAS', 'CHRISTMAS ISLAND');
INSERT INTO `pais` VALUES (101, 'ILHA DE CLIPPERTON', 'CLIPPERTON ISLAND');
INSERT INTO `pais` VALUES (102, 'ILHA DE JOÃO DA NOVA', 'JUAN DE NOVA ISLAND');
INSERT INTO `pais` VALUES (103, 'ILHA DE MAN', 'ISLE OF MAN');
INSERT INTO `pais` VALUES (104, 'ILHA DE NAVASSA', 'NAVASSA ISLAND');
INSERT INTO `pais` VALUES (105, 'ILHA EUROPA', 'EUROPA ISLAND');
INSERT INTO `pais` VALUES (106, 'ILHA NORFOLK', 'NORFOLK ISLAND');
INSERT INTO `pais` VALUES (107, 'ILHA TROMELIN', 'TROMELIN ISLAND');
INSERT INTO `pais` VALUES (108, 'ILHAS ASHMORE E CARTIER', 'ASHMORE AND CARTIER ISLANDS');
INSERT INTO `pais` VALUES (109, 'ILHAS CAIMAN', 'CAYMAN ISLANDS');
INSERT INTO `pais` VALUES (110, 'ILHAS COCOS (KEELING)', 'COCOS (KEELING) ISLANDS');
INSERT INTO `pais` VALUES (111, 'ILHAS COOK', 'COOK ISLANDS');
INSERT INTO `pais` VALUES (112, 'ILHAS DO MAR DE CORAL', 'CORAL SEA ISLANDS');
INSERT INTO `pais` VALUES (113, 'ILHAS FALKLANDS (ILHAS MALVINAS)', 'FALKLAND ISLANDS (ISLAS MALVINAS)');
INSERT INTO `pais` VALUES (114, 'ILHAS FEROE', 'FAROE ISLANDS');
INSERT INTO `pais` VALUES (115, 'ILHAS GEÓRGIA DO SUL E SANDWICH DO SUL', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS');
INSERT INTO `pais` VALUES (116, 'ILHAS MARIANAS DO NORTE', 'NORTHERN MARIANA ISLANDS');
INSERT INTO `pais` VALUES (117, 'ILHAS MARSHALL', 'MARSHALL ISLANDS');
INSERT INTO `pais` VALUES (118, 'ILHAS PARACEL', 'PARACEL ISLANDS');
INSERT INTO `pais` VALUES (119, 'ILHAS PITCAIRN', 'PITCAIRN ISLANDS');
INSERT INTO `pais` VALUES (120, 'ILHAS SALOMÃO', 'SOLOMON ISLANDS');
INSERT INTO `pais` VALUES (121, 'ILHAS SPRATLY', 'SPRATLY ISLANDS');
INSERT INTO `pais` VALUES (122, 'ILHAS VIRGENS AMERICANAS', 'UNITED STATES VIRGIN ISLANDS');
INSERT INTO `pais` VALUES (123, 'ILHAS VIRGENS BRITÂNICAS', 'BRITISH VIRGIN ISLANDS');
INSERT INTO `pais` VALUES (124, 'ÍNDIA', 'INDIA');
INSERT INTO `pais` VALUES (125, 'INDONÉSIA', 'INDONESIA');
INSERT INTO `pais` VALUES (126, 'IRÃO', 'IRAN');
INSERT INTO `pais` VALUES (127, 'IRAQUE', 'IRAQ');
INSERT INTO `pais` VALUES (128, 'IRLANDA', 'IRELAND');
INSERT INTO `pais` VALUES (129, 'ISLÂNDIA', 'ICELAND');
INSERT INTO `pais` VALUES (130, 'ISRAEL', 'ISRAEL');
INSERT INTO `pais` VALUES (131, 'ITÁLIA', 'ITALY');
INSERT INTO `pais` VALUES (132, 'JAMAICA', 'JAMAICA');
INSERT INTO `pais` VALUES (133, 'JAN MAYEN', 'JAN MAYEN');
INSERT INTO `pais` VALUES (134, 'JAPÃO', 'JAPAN');
INSERT INTO `pais` VALUES (135, 'JERSEY', 'JERSEY');
INSERT INTO `pais` VALUES (136, 'JIBUTI', 'DJIBOUTI');
INSERT INTO `pais` VALUES (137, 'JORDÂNIA', 'JORDAN');
INSERT INTO `pais` VALUES (138, 'KIRIBATI', 'KIRIBATI');
INSERT INTO `pais` VALUES (139, 'KOWEIT', 'KUWAIT');
INSERT INTO `pais` VALUES (140, 'LAOS', 'LAOS');
INSERT INTO `pais` VALUES (141, 'LESOTO', 'LESOTHO');
INSERT INTO `pais` VALUES (142, 'LETÓNIA', 'LATVIA');
INSERT INTO `pais` VALUES (143, 'LÍBANO', 'LEBANON');
INSERT INTO `pais` VALUES (144, 'LIBÉRIA', 'LIBERIA');
INSERT INTO `pais` VALUES (145, 'LÍBIA', 'LIBYAN ARAB JAMAHIRIYA');
INSERT INTO `pais` VALUES (146, 'LISTENSTAINE', 'LIECHTENSTEIN');
INSERT INTO `pais` VALUES (147, 'LITUÂNIA', 'LITHUANIA');
INSERT INTO `pais` VALUES (148, 'LUXEMBURGO', 'LUXEMBOURG');
INSERT INTO `pais` VALUES (149, 'MACAU', 'MACAO');
INSERT INTO `pais` VALUES (150, 'MACEDÓNIA', 'MACEDONIA');
INSERT INTO `pais` VALUES (151, 'MADAGÁSCAR', 'MADAGASCAR');
INSERT INTO `pais` VALUES (152, 'MALÁSIA', 'MALAYSIA');
INSERT INTO `pais` VALUES (153, 'MALAVI', 'MALAWI');
INSERT INTO `pais` VALUES (154, 'MALDIVAS', 'MALDIVES');
INSERT INTO `pais` VALUES (155, 'MALI', 'MALI');
INSERT INTO `pais` VALUES (156, 'MALTA', 'MALTA');
INSERT INTO `pais` VALUES (157, 'MARROCOS', 'MOROCCO');
INSERT INTO `pais` VALUES (158, 'MARTINICA', 'MARTINIQUE');
INSERT INTO `pais` VALUES (159, 'MAURÍCIA', 'MAURITIUS');
INSERT INTO `pais` VALUES (160, 'MAURITÂNIA', 'MAURITANIA');
INSERT INTO `pais` VALUES (161, 'MAYOTTE', 'MAYOTTE');
INSERT INTO `pais` VALUES (162, 'MÉXICO', 'MEXICO');
INSERT INTO `pais` VALUES (163, 'MIANMAR', 'MYANMAR BURMA');
INSERT INTO `pais` VALUES (164, 'MICRONÉSIA', 'MICRONESIA');
INSERT INTO `pais` VALUES (165, 'MOÇAMBIQUE', 'MOZAMBIQUE');
INSERT INTO `pais` VALUES (166, 'MOLDÁVIA', 'MOLDOVA');
INSERT INTO `pais` VALUES (167, 'MÓNACO', 'MONACO');
INSERT INTO `pais` VALUES (168, 'MONGÓLIA', 'MONGOLIA');
INSERT INTO `pais` VALUES (169, 'MONTENEGRO', 'MONTENEGRO');
INSERT INTO `pais` VALUES (170, 'MONTSERRAT', 'MONTSERRAT');
INSERT INTO `pais` VALUES (171, 'NAMÍBIA', 'NAMIBIA');
INSERT INTO `pais` VALUES (172, 'NAURU', 'NAURU');
INSERT INTO `pais` VALUES (173, 'NEPAL', 'NEPAL');
INSERT INTO `pais` VALUES (174, 'NICARÁGUA', 'NICARAGUA');
INSERT INTO `pais` VALUES (175, 'NÍGER', 'NIGER');
INSERT INTO `pais` VALUES (176, 'NIGÉRIA', 'NIGERIA');
INSERT INTO `pais` VALUES (177, 'NIUE', 'NIUE');
INSERT INTO `pais` VALUES (178, 'NORUEGA', 'NORWAY');
INSERT INTO `pais` VALUES (179, 'NOVA CALEDÓNIA', 'NEW CALEDONIA');
INSERT INTO `pais` VALUES (180, 'NOVA ZELÂNDIA', 'NEW ZEALAND');
INSERT INTO `pais` VALUES (181, 'OMÃ', 'OMAN');
INSERT INTO `pais` VALUES (182, 'PAÍSES BAIXOS', 'NETHERLANDS');
INSERT INTO `pais` VALUES (183, 'PALAU', 'PALAU');
INSERT INTO `pais` VALUES (184, 'PALESTINA', 'PALESTINE');
INSERT INTO `pais` VALUES (185, 'PANAMÁ', 'PANAMA');
INSERT INTO `pais` VALUES (186, 'PAPUÁSIA-NOVA GUINÉ', 'PAPUA NEW GUINEA');
INSERT INTO `pais` VALUES (187, 'PAQUISTÃO', 'PAKISTAN');
INSERT INTO `pais` VALUES (188, 'PARAGUAI', 'PARAGUAY');
INSERT INTO `pais` VALUES (189, 'PERU', 'PERU');
INSERT INTO `pais` VALUES (190, 'POLINÉSIA FRANCESA', 'FRENCH POLYNESIA');
INSERT INTO `pais` VALUES (191, 'POLÓNIA', 'POLAND');
INSERT INTO `pais` VALUES (192, 'PORTO RICO', 'PUERTO RICO');
INSERT INTO `pais` VALUES (193, 'PORTUGAL', 'PORTUGAL');
INSERT INTO `pais` VALUES (194, 'QUÉNIA', 'KENYA');
INSERT INTO `pais` VALUES (195, 'QUIRGUIZISTÃO', 'KYRGYZSTAN');
INSERT INTO `pais` VALUES (196, 'REINO UNIDO', 'UNITED KINGDOM');
INSERT INTO `pais` VALUES (197, 'REPÚBLICA CHECA', 'CZECH REPUBLIC');
INSERT INTO `pais` VALUES (198, 'REPÚBLICA DOMINICANA', 'DOMINICAN REPUBLIC');
INSERT INTO `pais` VALUES (199, 'ROMÉNIA', 'ROMANIA');
INSERT INTO `pais` VALUES (200, 'RUANDA', 'RWANDA');
INSERT INTO `pais` VALUES (201, 'RÚSSIA', 'RUSSIAN FEDERATION');
INSERT INTO `pais` VALUES (202, 'SAHARA OCCIDENTAL', 'WESTERN SAHARA');
INSERT INTO `pais` VALUES (203, 'SALVADOR', 'EL SALVADOR');
INSERT INTO `pais` VALUES (204, 'SAMOA', 'SAMOA');
INSERT INTO `pais` VALUES (205, 'SANTA HELENA', 'SAINT HELENA');
INSERT INTO `pais` VALUES (206, 'SANTA LÚCIA', 'SAINT LUCIA');
INSERT INTO `pais` VALUES (207, 'SANTA SÉ', 'HOLY SEE');
INSERT INTO `pais` VALUES (208, 'SÃO CRISTÓVÃO E NEVES', 'SAINT KITTS AND NEVIS');
INSERT INTO `pais` VALUES (209, 'SÃO MARINO', 'SAN MARINO');
INSERT INTO `pais` VALUES (210, 'SÃO PEDRO E MIQUELÃO', 'SAINT PIERRE AND MIQUELON');
INSERT INTO `pais` VALUES (211, 'SÃO TOMÉ E PRÍNCIPE', 'SAO TOME AND PRINCIPE');
INSERT INTO `pais` VALUES (212, 'SÃO VICENTE E GRANADINAS', 'SAINT VINCENT AND THE GRENADINES');
INSERT INTO `pais` VALUES (213, 'SEICHELES', 'SEYCHELLES');
INSERT INTO `pais` VALUES (214, 'SENEGAL', 'SENEGAL');
INSERT INTO `pais` VALUES (215, 'SERRA LEOA', 'SIERRA LEONE');
INSERT INTO `pais` VALUES (216, 'SÉRVIA', 'SERBIA');
INSERT INTO `pais` VALUES (217, 'SINGAPURA', 'SINGAPORE');
INSERT INTO `pais` VALUES (218, 'SÍRIA', 'SYRIA');
INSERT INTO `pais` VALUES (219, 'SOMÁLIA', 'SOMALIA');
INSERT INTO `pais` VALUES (220, 'SRI LANCA', 'SRI LANKA');
INSERT INTO `pais` VALUES (221, 'SUAZILÂNDIA', 'SWAZILAND');
INSERT INTO `pais` VALUES (222, 'SUDÃO', 'SUDAN');
INSERT INTO `pais` VALUES (223, 'SUÉCIA', 'SWEDEN');
INSERT INTO `pais` VALUES (224, 'SUÍÇA', 'SWITZERLAND');
INSERT INTO `pais` VALUES (225, 'SURINAME', 'SURINAME');
INSERT INTO `pais` VALUES (226, 'SVALBARD', 'SVALBARD');
INSERT INTO `pais` VALUES (227, 'TAILÂNDIA', 'THAILAND');
INSERT INTO `pais` VALUES (228, 'TAIWAN', 'TAIWAN');
INSERT INTO `pais` VALUES (229, 'TAJIQUISTÃO', 'TAJIKISTAN');
INSERT INTO `pais` VALUES (230, 'TANZÂNIA', 'TANZANIA');
INSERT INTO `pais` VALUES (231, 'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO', 'BRITISH INDIAN OCEAN TERRITORY');
INSERT INTO `pais` VALUES (232, 'TERRITÓRIO DAS ILHAS HEARD E MCDONALD', 'HEARD ISLAND AND MCDONALD ISLANDS');
INSERT INTO `pais` VALUES (233, 'TIMOR-LESTE', 'TIMOR-LESTE');
INSERT INTO `pais` VALUES (234, 'TOGO', 'TOGO');
INSERT INTO `pais` VALUES (235, 'TOKELAU', 'TOKELAU');
INSERT INTO `pais` VALUES (236, 'TONGA', 'TONGA');
INSERT INTO `pais` VALUES (237, 'TRINDADE E TOBAGO', 'TRINIDAD AND TOBAGO');
INSERT INTO `pais` VALUES (238, 'TUNÍSIA', 'TUNISIA');
INSERT INTO `pais` VALUES (239, 'TURKS E CAICOS', 'TURKS AND CAICOS ISLANDS');
INSERT INTO `pais` VALUES (240, 'TURQUEMENISTÃO', 'TURKMENISTAN');
INSERT INTO `pais` VALUES (241, 'TURQUIA', 'TURKEY');
INSERT INTO `pais` VALUES (242, 'TUVALU', 'TUVALU');
INSERT INTO `pais` VALUES (243, 'UCRÂNIA', 'UKRAINE');
INSERT INTO `pais` VALUES (244, 'UGANDA', 'UGANDA');
INSERT INTO `pais` VALUES (245, 'URUGUAI', 'URUGUAY');
INSERT INTO `pais` VALUES (246, 'USBEQUISTÃO', 'UZBEKISTAN');
INSERT INTO `pais` VALUES (247, 'VANUATU', 'VANUATU');
INSERT INTO `pais` VALUES (248, 'VENEZUELA', 'VENEZUELA');
INSERT INTO `pais` VALUES (249, 'VIETNAME', 'VIETNAM');
INSERT INTO `pais` VALUES (250, 'WALLIS E FUTUNA', 'WALLIS AND FUTUNA');
INSERT INTO `pais` VALUES (251, 'ZÂMBIA', 'ZAMBIA');
INSERT INTO `pais` VALUES (252, 'ZIMBABUÉ', 'ZIMBABWE');

-- ----------------------------
-- Table structure for percursos
-- ----------------------------
DROP TABLE IF EXISTS `percursos`;
CREATE TABLE `percursos`  (
  `percursoId` int(11) NOT NULL AUTO_INCREMENT,
  `percursoNome` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `percursoKm` int(11) NOT NULL,
  `percursoImgUrl` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`percursoId`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 10 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of percursos
-- ----------------------------
INSERT INTO `percursos` VALUES (5, 'tey', 0, 'WhatsApp Image 2021-04-24 at 12.02.29.jpeg');
INSERT INTO `percursos` VALUES (8, 'éfns', 22, 'IMG-2813.jpg');
INSERT INTO `percursos` VALUES (9, 'dsa', 4, 'IMG-2813.jpg');

SET FOREIGN_KEY_CHECKS = 1;
